ControleContatos/Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;

namespace ControleContatos.Models
{
    public class ContatoModel
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Digite o Nome do Contato")]

        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite o Email do Contato")]
        [EmailAddress(ErrorMessage = "O Email informado nao é válido.") ]

        public string Email { get; set; }
        [Required(ErrorMessage = "Digite o Celular do Contato")]
        [Phone(ErrorMessage = "O Celular informado nao é válido.")]

        public string Celular { get; set; }


    }
}

ControleContatos/Models/ErrorViewModel.cs
namespace ControleContatos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleContatos/Controllers/ContatoController.cs
using ControleContatos.Models;
using ControleContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleContatos.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;

        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }

        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();
            return View(contatos);
        }

        public IActionResult Create()
        {

            return View();
        }

        public IActionResult Edit(int id)
        {
           ContatoModel contato = _contatoRepositorio.ListarporID(id);
            return View(contato);
        }

        public IActionResult Delete(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarporID(id);
            return View(contato);
        }

        public IActionResult DeleteContato(int id)
        {
            try
            {
                bool apagado = _contatoRepositorio.Apagar(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Contato apagado com Sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops! Nao conseguimos apagar seu contato.";
                }

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["MensagemErro"] = "Ops! Nao conseguimos apagar seu contato.";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato cadastrado com Sucesso!";
                    return RedirectToAction("Index");
                }

                return View("Create", contato);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops! Nao conseguimos cadastrar o seu Contato, tente novamente. Detalhe do Erro: {erro.Message } ";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Atualizar(contato);
                    TempData["MensagemSucesso"] = "Contato alterado com Sucesso!";
                    return RedirectToAction("Index");
                }

                return View("Edit", contato);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops! Nao conseguimos atualizar o seu Contato, tente novamente. Detalhe do Erro: {erro.Message} ";
                return RedirectToAction("Index");
            }
        }
    }
}

ControleContatos/Controllers/HomeController.cs
using ControleContatos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ControleContatos.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControleContatos/Views/Contato/Create.cshtml
@model ContatoModel

<div class="text-center">

    <h1 class="display-4">Cadastrar Contato</h1>
</div>

<form asp-controller="Contato" asp-action="Criar" method="post">
          <div class="form-grupo">
            <label for="name" >Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Digite seu Nome" />
            @Html.ValidationMessageFor(x => x.Nome)
          </div>

          <div class="form-grupo">
            <label for="email" >Email</label>
            <input type="text" asp-for="Email" class="form-control" placeholder="Digite seu Email" />
            @Html.ValidationMessageFor(x => x.Email)
          </div>

           <div class="form-grupo">
            <label for="celular" >Telefone</label>
            <input type="text" asp-for="Celular" class="form-control" placeholder="Digite seu Telefone" />
            @Html.ValidationMessageFor(x => x.Celular)
          </div>

        <br />
        <br />
         
          <button type="submit" class="btn btn-success" >Cadastrar</button>
          <a class="btn btn-secondary " asp-controller="Contato" asp-action="Index"  role="button"> Voltar </a>
        </form>

ControleContatos/Views/Contato/Delete.cshtml
@model ContatoModel

<div class="text-center">

    <h3 >Deseja apagar o Contato (@Model.Nome)? </h3>
    <a class="btn btn-danger" role="button" asp-controller="Contato" asp-action="DeleteContato" asp-route-id="@Model.ID"> Excluir </a>
    <a class="btn btn-secondary" role="button" asp-controller="Contato" asp-action="Index" > Cancelar </a>
</div>

ControleContatos/Views/Contato/DeleteContato.cshtml
<div class="text-center">

    <h3 >Deseja apagar o Contato?</h3>
    <a class="btn btn-danger" role="button" asp-controller="Contato" asp-action="DeleteContato" > Excluir </a>
    <a class="btn btn-secondary" role="button" asp-controller="Contato" asp-action="Index" > Cancelar </a>
</div>

ControleContatos/Views/Contato/Edit.cshtml
@model ContatoModel

<div class="text-center">

    <h1 class="display-4">Editar Contato</h1>
</div>


<form asp-controller="Contato" asp-action="Alterar" method="post">
          <input type="hidden" asp-for="ID"> </input>
          <div class="form-grupo">
            <label for="name" >Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Digite seu Nome" />
            @Html.ValidationMessageFor(x => x.Nome)
          </div>

          <div class="form-grupo">
            <label for="email" >Email</label>
            <input type="text" asp-for="Email" class="form-control" placeholder="Digite seu Email" />
            @Html.ValidationMessageFor(x => x.Email)
          </div>

           <div class="form-grupo">
            <label for="celular" >Telefone</label>
            <input type="text" asp-for="Celular" class="form-control" placeholder="Digite seu Telefone" />
            @Html.ValidationMessageFor(x => x.Celular)
          </div>

        <br />
        <br />
         
          <button type="submit" class="btn btn-success" >Alterar</button>
          <a class="btn btn-secondary " asp-controller="Contato" asp-action="Index"  role="button"> Voltar </a>
        </form>

ControleContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem de Contatos";
}

<div class="text-center">

    <div class=""> 
        <a role="button" class="btn btn-light" asp-controller="Contato" asp-action="Create"> Adicionar novo contato </a>

       <br />

        @if (TempData["MensagemSucesso"] != null)
        {
           <div class="alert alert-success" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert"> X </button>
          @TempData["MensagemSucesso"]
        </div> 
        }

        @if (TempData["MensagemErro"] != null)
        {
           <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert"> X </button>
          @TempData["MensagemErro"]
          </div>        
        }


    </div>

        <br></br>

        

    <h1 class="display-4">Listagem de Contatos</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Celular</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody> 
                @if (Model != null && Model.Any())
                {
                    foreach (ContatoModel contato in Model)
                    {
                      <tr>
                          <th scope="row">@contato.ID</th>
                          <td>@contato.Nome</td>
                          <td>@contato.Email</td>
                          <td>@contato.Celular</td>
                          <td>
                              <div class="btn-group" role="group">
                                  <a role="button" class="btn btn-primary" asp-route-id="@contato.ID" asp-controller="Contato" asp-action="Edit" >Editar</a>
                                  <a role="button" class="btn btn-danger" asp-route-id="@contato.ID" asp-controller="Contato" asp-action="Delete" >Apagar</a>
                              </div>
                          </td>
                      </tr>
                    }
                }
            
    
  </tbody>
</table>

</div>

ControleContatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <p>Sistema de controle de Contatos</p>
</div>

ControleContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControleContatos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Contatos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Controle de Contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>